spring:
  profiles:
    active: local

---
spring:
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        storage_engine: innodb
  session:
    store-type: jdbc
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  cache:
    jcache:
      config: classpath:ehcache.xml
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
# password: ENC(txE8aNs0QkHSsVPRS7gVldm90F5SBwPW8rY/G8okDaY=) ## test
---
# local 환경
spring:
  profiles: local
  datasource:
    hikari:
      data: classpath:data.sql
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
#      password: password
server:
  port: 8080

---
# 운영 환경 set1
spring:
  profiles: set1
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
#      password: password
server:
  port: 8081

---
# 운영 환경 set2
spring:
  profiles: set2
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
#      password: password
server:
  port: 8082